### ISSUE TITLE
on install: Notice: Undefined index: qwcrm_config

### ISSUE THREAD

**Issue by sun-it** [shoulders/qwcrm#1091]
In QWcrm 3.1.0, on install i have this error:
Notice: Undefined index: qwcrm_config in ...install_stage1_database_connection_block.tpl.php on line 64

QWcrm 3.1.0
Apache 2.4.34
PHP 7.2.8
MySQL 5.7.22

**Comment by sun-it** [comment]
There is a Screenshot
[Install QWcrm.pdf](https://github.com/shoulders/qwcrm/files/2339471/Install.QWcrm.pdf)

**Comment by shoulders** [comment]
I can help later on but it looks like the install process was not completed in a previous atempt. Best solution to this is to start again (delete all files etc..) but using 3.0.0

version 3.1.0 is not released and is not complete. (it is not far off)

I will have to do some testing on your version of PHP but it should not be an issue.

**Comment by sun-it** [comment]
Thank you for response.
The Screenshot from 3.0.0
[Install QWcrm_3.0.0.pdf](https://github.com/shoulders/qwcrm/files/2339514/Install.QWcrm_3.0.0.pdf)

Apache 2.4.34
PHP 7.2.8
MySQL 5.7.22

**Comment by shoulders** [comment]
long shot, try disabling xdebug.

**Comment by sun-it** [comment]
The Screenshot from 3.0.0 without xdebug
[Install QWcrm_3.0.0-2.pdf](https://github.com/shoulders/qwcrm/files/2339557/Install.QWcrm_3.0.0-2.pdf)

**Comment by shoulders** [comment]
I think you have php error reporting turned up to much. Try disabling php error reporting off.

This has been fixed in the new version

On 31 August 2018 10:47:35 BST, sun-it <notifications@github.com> wrote:
>The Screenshot from 3.0.0 without xdebug
>[Install
>QWcrm_3.0.0-2.pdf](https://github.com/shoulders/qwcrm/files/2339557/Install.QWcrm_3.0.0-2.pdf)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/1091#issuecomment-417613227

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by shoulders** [comment]
did turning PHP erros down fix it?

**Comment by sun-it** [comment]
Not at all. Database was installed, but next step (for first User registration) was blank page.
Also i try to install both 3.0.0 and 3.1.0 with PHP 7.0.31, without success. Installer brake on many error messages like: "mobile_phone has not default value" or "last_active has not default value"...

**Comment by shoulders** [comment]
I will do some work on it this weekend so I can fix your issues. I am not sure what is causing this.

I want to try and have the new version released with 2 weeks which has none of these issues

On 31 August 2018 20:49:52 BST, sun-it <notifications@github.com> wrote:
>Not at all. Database was installed, but next step (for first User
>registration) was blank page.
>Also i try to install both 3.0.0 and 3.1.0 with PHP 7.0.31, without
>success. Installer brake on many error messages like: "mobile_phone has
>not default value" or "last_active has not default value"...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/1091#issuecomment-417771850

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by shoulders** [comment]
the last errors you sent me are are definately because PHP error reporting is on. You need to turn PHP error reporting and xdebug off.

I have just fixed most of these in the new version so PHP error reporting and xdebug will make no difference so my solution here is a quick workaround.
