### ISSUE TITLE
Installation issue overview

### ISSUE THREAD

**Issue by disorganised-mess** [shoulders/qwcrm#1317]
Thought I'd give you a quick update on some of the installation issues that have been faced. This is a culmination of things I've tried and troubleshooting results. Some text combined from the readme.

QWcrm requires:
A web server with PHP 5.6+ and MySQL 5.0.0+.
Ensure that 'php-intl', 'php-xml' and 'php-mbstring' are installed.
The above done and works on an RPI2 w/ Raspbian Stretch. Should work for most others as well.
I think the issue most folks face will be that the extra packages aren't installed by default on a fresh server installation
If using XAMPP:
    uncomment ';extensions-php_intl.dll to enable the funcion locale_accept_from_http()
    reduce error reporting to 'error_reporting = E_ALL & ~E_NOTICE'
It may be worth putting this information in the "Wiki" section here, so it can be easily referenced.
Keep up the work looking forward to future versions and just trying to contribute where I can.

**Comment by shoulders** [comment]
@disorganised-mess thanks for the thorough feedback it is appreciated. 

v3.1.0 has a lot of changes
- During the installation it now sets out mi

**Comment by disorganised-mess** [comment]
I hoped this would give you a single reference point for anyone else having install troubles. I had just put together the results of my own troubleshooting with some points from other "Support" posts. the 'php-mbstring' and 'php-xml' solved a couple of "white screen" issues instances for me. Happy to help where I can.

**Comment by shoulders** [comment]
- Enabling **extensions-php_intl.dll** is not mandatory. This only allows for automatic language detection from the browser.
- do not hide error reporting to get QWcrm workign. There should be no errors displayed. If there is there is an issue.

**Comment by shoulders** [comment]
I have check that these issues have been addressed.

'php-xml' and 'php-mbstring' are installed on most public webservers. I cant remember if the version of my xampp has these on by default but thoses using xampp should be developers only and know how to turn these on.
