### ISSUE TITLE
accessories should not be on the print page

### ISSUE THREAD

**Issue by rwebb3** [shoulders/qwcrm#137]
when creating a work order there is no location to add accessories (things such as power cables, USB cables, SD cards, etc). This is instead found on the "print work order" page, which doesn't really make sense, especially since it has to be entered twice (once for store copy and once for customer copy). 
That information should be added when you create the work order. The printing page should only be for printing. The number of accessories also shouldn't be a set number, but perhaps having a maximum number would be a good idea.

**Comment by shoulders** [comment]
Hi Robert,

Is this fault about v2.93 or have you got my new version running. I have spent a lot of time making the template separate so before long i can look at most aspects of the workflow.

The print templates that I have made were really to add the functionality that was there in old versions and as a base for future improvements.

when you say "accessories (things such as power cables, USB cables, SD cards, etc)" what is the purpose of adding them to the work order?

1) stuff the customer brings with them?
2) parts you want to sell to them?

thanks

**Comment by rwebb3** [comment]
sorry. I'm actually working on getting your version running to test on my web server. I assumed you hadn't had time to change it yet from 2.93. but yes accessories would be additional items that customers bring in with them.

**Comment by shoulders** [comment]
I have massively changed the code and files. It will function almost the same at the minute though as I am just finishing the code tidy up. There are some extra bits though.

If you want a play I think there are a couple of tables/columns missing from the database. If you add these it should work, but definitely dont use it for real jobs.

**Comment by rwebb3** [comment]
oh yeah. I have no intention of using it for anything real yet. I was just wanting to play around with it and possibly contribute some things.

**Comment by shoulders** [comment]
if you dont manage to get it working, let me know and i will bodge the installer so things work. I wont be able to do that until next week as I have visiting relatives and i need to give my website some love

**Comment by rwebb3** [comment]
I did not manage to get it working. I kept getting SQL errors, which I managed to fix/work around, but now all I get is "The File System and Database versions do not match, run the upgrade routine" so I tried to do that, but I think the upgrades are actually older than what you've changed so I'm not sure what to do. is the version number in a config file somewhere?

**Comment by shoulders** [comment]
Upgrade dosnt work. Not fix yet. Find defines.php and change version number to 2.9.3. This should get around the validation. PS. I will get my forum working at quantumwarp.com to keep github clean for features etc..

On 30 September 2016 23:01:16 BST, Robert Webb <notifications@github.com> wrote:
>I did not manage to get it working. I kept getting SQL errors, which I
>managed to fix/work around, but now all I get is "The File System and
>Database versions do not match, run the upgrade routine" so I tried to
>do that, but I think the upgrades are actually older than what you've
>changed so I'm not sure what to do. is the version number in a config
>file somewhere?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/137#issuecomment-250862653

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by shoulders** [comment]
Hi Robert,

I can't find a PM systems so I will post here.

I have done this progress report so you can see what is going on.

https://quantumwarp.com/blog/qwcrm-first-progress-report

shoulders

**Comment by shoulders** [comment]
there is a comments and notes section of the work order and this is what they should be used for.
