### ISSUE TITLE
( ! ) Warning: require(libraries/vendor/autoload.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mustapha74511** [shoulders/qwcrm#1400]
hello, itry to install it on localhost but seems i have errors like :

( ! ) Warning: require(libraries/vendor/autoload.php): failed to open stream: No such file or directory in /Users/root1/mysites/src/libraries/qframework/qframework.php on line 112

( ! ) Fatal error: require(): Failed opening required 'libraries/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php7.0.32/lib/php') in /Users/root1/mysites/src/libraries/qframework/qframework.php on line 112
 ---
the file libraries/vendor/autoload.php is not exist any idea?

**Comment by shoulders** [comment]
download from here

https://github.com/shoulders/qwcrm/releases

The version in the repo will not work as is. Also the new verion will be out shortly
