### ISSUE TITLE
should paypal transaction ID be mandatory

### ISSUE THREAD

**Issue by shoulders** [shoulders/qwcrm#1508]
cheque numbers and paypal id, should these be mandatory in payments?

**Comment by RoyceWhitaker** [comment]
Creating an option to require these would be good.
My work uses the Square terminals which gives us a 5 digit receipt number that could also go in that spot. Maybe name it something generic like "External receipt number"

**Comment by shoulders** [comment]
maybe another payment method could be added

**Comment by shoulders** [comment]
if it is not mandatory i will not fill it in. Give it a go mandatory. I can possbly use this later to build a paypal search link
