### ISSUE TITLE
Field db host to short 

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1580]
Tried to set system up and encountered multiple issues. Will separate them.

Issue one:
Field db host to short (20 chars). Should be significant more (50 or so).

**Comment by shoulders** [comment]
I will look into what the maximum MySQL database size is. cPanel hosting is about 20 (or it was). I will see what their limits are becasue I will use that as my benchmark.

**Comment by dirigit** [comment]
DB is ok, it's limited by form field in template.
