### ISSUE TITLE
Administrator cannot be created because passwords dont match

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1582]
Create administrator not possible with Firefox at least.

Tried it with required fields only as well as filling all fields.

Next button does not work.

**Comment by dirigit** [comment]
Problem has been non matching passwords (?).

commented disable button in install_administrator_account_block.tpl as well.

**Comment by shoulders** [comment]
can you send screen shots or some more information becasue I am not sure what is happening.

Are you pasting in the passwords? Can you try typing them in instead. It might be that I made the password match trigger event on keypress only.

**Comment by dirigit** [comment]
Encoutered it is a problem with sequence of entering data. Comparison is correct when tabbing from top down through form and filling fields, otherwise it's false.
