### ISSUE TITLE
PHP version check should not use sub-version

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1583]
PHP version check only up to 7.2.**0**.

Don't believe it's a good idea to limit sub-sub-version to .0.

**Comment by shoulders** [comment]
this is intentional becasue PHP 7.2.0 is more strict on session handling and causes issues.

I now know that the 0.0.x is tha securrity patch rather than functionality change but I needed to get the 3.1.0 release out.

This will be fixed in #1338 and  #1141
