### ISSUE TITLE
Internationalization not working

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1584]
Installation of translation or changing language to manual copied language not possible.

Manual changes in configuration will be overwritten.

**Comment by shoulders** [comment]
Hi, you cannot just copy the language files. You need to use poedit.

I will go through these issue deeper later on today.

Thanks

On 16 June 2019 10:13:36 BST, dirigit <notifications@github.com> wrote:
>Installation of translation or changing language to manual copied
>language not possible.
>
>Manual changes in configuration will be overwritten.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/1584

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by dirigit** [comment]
Translation is done via poedit. .po and .mo copied to new language directory.

**Comment by shoulders** [comment]
The {t}{/t} strings in the .TPL files will not be transalted without my customer .php file/interpreter I wrote which will cause the default/english/en-GB text to be displayed.

**Comment by dirigit** [comment]
Found reason for not being able to change default language:

QWCRM does not check for translations - English is hardcoded in administrator/config.tpl.

**Comment by dirigit** [comment]
Argl... ok, tested other possibility:

Automatic translation works when having language in directory with two-letter code of language (ie en instead of en_US). Changing default language is not possible because of hard coding.

**Comment by dirigit** [comment]
I like to recommend to change behaviour to taking four-letter codes into respect.

There are some languages with differences ...

I.e. English - en_IN, en_US, en_GB; German - de_DE (default fallback), de_AT, de_CH; fr_CA, fr_FR (default); pt_BR, pt_PT (default); zh_CN, zh_HK, zh_TW; ...

**Comment by shoulders** [comment]
I thought this was already the case. If you look in the LC_MESSAGES they are all 4 letters. It might be the browser automatic detection has 2 letters because of how they work. However I will look at this again.

On 17 June 2019 08:36:18 BST, dirigit <notifications@github.com> wrote:
>I like to recommend to change behaviour to taking four-letter codes
>into respect.
>
>There are some languages with differences ...
>
>I.e. English - en_IN, en_US, en_GB; German - de_DE (default fallback),
>de_AT, de_CH; fr_CA, fr_FR (default); pt_BR, pt_PT (default); zh_CN,
>zh_HK, zh_TW; ...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/1584#issuecomment-502569197

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by shoulders** [comment]
This might just be the default language.

If you can post a mo and po in their correct folder for another language with changes tot eh text on the dashboard that would help. Don't forget you need to use that php script otherwise no .TPL will be translated.

I really appreciate the feedback and I will hopefully get all of these fixed for the next small release (this week or next)

On 17 June 2019 08:17:45 BST, dirigit <notifications@github.com> wrote:
>Found reason for not being able to change default language:
>
>QWCRM does not check for translations - English is hardcoded in
>administrator/config.tpl.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/1584#issuecomment-502563998

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by dirigit** [comment]
In attachment a partial translation to German. Must be in directory "de" (not de_DE) to work.
It's far from completness - must click throug app to see what's meant in each case.


[LC_MESSAGES.zip](https://github.com/shoulders/qwcrm/files/3296286/LC_MESSAGES.zip)

**Comment by dirigit** [comment]
That's all ok regarding default language.

But, in case there is another language which works with automatic detection there is still no chance to choose it as default for whole site. Fallback as rescue is another kind of animal IMHO ;)

**Comment by shoulders** [comment]
in reguards for the default language I have created a new issue #1588

**Comment by shoulders** [comment]
The automatic translations is working perfectly on my browser.

I used this firefox extension to check by changing the accept-header

https://addons.mozilla.org/en-GB/firefox/addon/language-switcher/
