### ISSUE TITLE
Let User choose preferred language

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1708]
Let user choose preferred language when there are multiple possibilities.

**Comment by shoulders** [comment]
Currently this can be set for all of QWcrm.

Is this so if you have several staff at work that speak different languages?

**Comment by dirigit** [comment]
Currently languages in use are German, English and Russian. More might come ...

**Comment by shoulders** [comment]
Did you want it per user?

This can be a feature request.

p.s. The lannguage strings will be getting altered soon. POEdit should still be ok. When the translations are done for v3.2.0 can I have them to put on webslte and then I either include them in QWcrm or make availabel for download.
