### ISSUE TITLE
SQL error in 3_1_2  upgrade_database.sql

### ISSUE THREAD

**Issue by shoulders** [shoulders/qwcrm#1716]
when upgrading from 3.1.1 to 3.1.2

````sql
-- Fix missing employee_id on closed Workorders
UPDATE #__workorder_records SET employee_id = closed_by WHERE employee_id = '' AND closed_by != '';
````
generates the following error message
````
::1,-,[13/Jan/2020:14:11:35 +0000],-,3.1.2,upgrade,"Performed SQL query successfully : Unrecognised SQL Command","",""
````
Is this caused by my  code parsing the actual SQL code and returning a truncated version

the command does run successfully.

**Comment by dirigit** [comment]
Are you sure to have no empty strings (spaces only and the like)?

I would test for this with len or so. I would also try to use something like "closed_by **<>** ''" instead of °closed_by **!=** '' °.

Even when table definition says "not null" coalesce is a handy function as well for such problems ...

**Comment by shoulders** [comment]
hi

- i dont know what coalesce is
- I need to use **closed_by != ''"** becasue of how smarty handles data in the template

**Comment by dirigit** [comment]
- coalesce is a SQL function. Explanation and nice example to understand it better can be found eg here: https://stackoverflow.com/questions/17104329/how-to-use-coalesce-in-mysql
- mySQL <> ignores empty strings at comparisons (if nothing has been changed between versions). Don't know if != has same behaviour.

**Comment by shoulders** [comment]
it probably does the same thing most fo the time, but on some edge cases there might be some differences.

**Comment by shoulders** [comment]
github has a bug?

**Comment by shoulders** [comment]
see https://github.com/shoulders/qwcrm/blob/e5692e7333ba8d549525986b3ae0fcbe56fc5b0b/src/components/_includes/Setup.php#L838

I just need to change the message displayed to something better and chekc the handling. The actual SQL is executing as required.

**Comment by shoulders** [comment]
the "Unrecognised SQL Command" is issued becasue i did not add ``
