### ISSUE TITLE
Schedule not saving with correct start and end time - 60 mins is being added

### ISSUE THREAD

**Issue by yasitha1989** [shoulders/qwcrm#1747]
How to stop 60 minutes adding to end time

related to #1013

**Comment by shoulders** [comment]
can you explain more please.

Pictures would be helpful.

**Comment by yasitha1989** [comment]
**Wen we set Schedule to 14:00 hrs 15:00 hrs it's saved to 15:00 hrs to 16:00**
![2020-03-04 (2)](https://user-images.githubusercontent.com/1142431/75859587-4b173d00-5e20-11ea-8ae6-cbd69b2e5abe.png)
![2020-03-04](https://user-images.githubusercontent.com/1142431/75859592-4ce10080-5e20-11ea-88a1-d5acdb256aed.png)

**Comment by shoulders** [comment]
I have just set a schedule on my test for **14.00** --> **15.00**

![image](https://user-images.githubusercontent.com/319997/75860365-9a934400-5df3-11ea-89b1-dd89ab67ab72.png)

Gives

![image](https://user-images.githubusercontent.com/319997/75860397-a848c980-5df3-11ea-81c4-f0feb44205ac.png)

- It is working on mine v3.1.3
- can you recheck?
- is the time on your server correct?
- I am not sure what is causing this.

**Comment by yasitha1989** [comment]
I'm using shared hosting server with v3.1.3.
 I can't do it like you. I have seen some other one post same in this forum https://github.com/shoulders/qwcrm/issues/1013.

**Comment by shoulders** [comment]
- is the time on your server correct?
- if you edit this schedule, what are the times shown?

**Comment by yasitha1989** [comment]
I think Server time is different than country time but it more than one hour.
Schedule editing screen shot attached 
![2020-03-04](https://user-images.githubusercontent.com/1142431/75862149-7ac84400-5e24-11ea-92a2-3353d8cb3746.png)

**Comment by yasitha1989** [comment]
I think Server time is different than country time but it more than one hour.
Schedule editing screen shot attached 
![2020-03-04 (6)](https://user-images.githubusercontent.com/1142431/75862477-05a93e80-5e25-11ea-82c6-4a14ce23059e.png)

**Comment by shoulders** [comment]
- ok, so when you edit the schedule the times are the same as shown on daily = good
- do you know why the dates are missing?
- what happens when you click submit on the edit schedule

**Comment by yasitha1989** [comment]
I don't know reason for date missing. 
When it submit again automatically going forward to next hour.
![2020-03-04 (9)](https://user-images.githubusercontent.com/1142431/75863431-78ff8000-5e26-11ea-928b-196cc6996415.png)

**Comment by yasitha1989** [comment]
php time
![2020-03-04 (16)](https://user-images.githubusercontent.com/1142431/75864401-efe94880-5e27-11ea-9e3f-8ea700ab7897.png)
![2020-03-04 (11)](https://user-images.githubusercontent.com/1142431/75864408-f5469300-5e27-11ea-83d2-88501073d8c6.png)

**Comment by shoulders** [comment]
and by the looks of it is not storing the date.

last thing for you to try, can you use another browser and see what happens.

**Comment by yasitha1989** [comment]
I had try with Microsoft Edge. Problem is still same
![2020-03-04 (18)](https://user-images.githubusercontent.com/1142431/75871233-40fe3a00-5e32-11ea-9f00-33394206e8e6.png)
![2020-03-04 (19)](https://user-images.githubusercontent.com/1142431/75871242-43609400-5e32-11ea-8651-4b67f2425e28.png)

**Comment by shoulders** [comment]
- I need to get access to investigate further.
- Are you able to setup a separate installation so I can log into (and FTP) so i can see what is going on.
- I wont be able to do this to this evening (my time / UK).
- If you send me a message via https://quantumwarp.com/contact with the details it prevents my email getting exposed.

Thanks for reporting the issue.

**Comment by yasitha1989** [comment]
Login details send. Thanks for kindly support

**Comment by shoulders** [comment]
Can you resend. My server credentials were wrong.

Sorry.

**Comment by shoulders** [comment]
can you resend username and password please.

**Comment by shoulders** [comment]
no response

**Comment by yasitha1989** [comment]
Today I was fully reinstall it. now it's working perfectly. Thanks for your kindly attention

**Comment by shoulders** [comment]
just quickly, what do you think was the issue?

**Comment by yasitha1989** [comment]
I was read code by code but I can't find place in this issue generated.  After fresh copy installation with new database still it working perfectly
