### ISSUE TITLE
Dollar symbol being stripped from password

### ISSUE THREAD

**Issue by JamesSwift** [shoulders/qwcrm#1788]
**Describe the bug**
During setup, when entering the database password, it was reporting that it was the wrong password. A little investigation showed that the dollar $ symbol was being stripped form the entered password. I am using the latest release.

**System information (please complete the following information)**

Joomla version: ?
Kunena version: ?
Php version: 7.4
Database version: 10.3.22-MariaD

**Comment by shoulders** [comment]
i have just tried in my dev version and it allows the use of $ in the password.
