### ISSUE TITLE
Installtion error during 'Creating an administrator' step

### ISSUE THREAD

**Issue by JamesSwift** [shoulders/qwcrm#1789]
**Describe the bug**
So, this is hard to describe, and I've tried to track this down to get some useful information for you but there are several roadblocks. I'me seeing the error `Undefined index: error_component`. However, this is because `$_smarty_tpl->tpl_vars` is empty. I'm not familiar with your framework, but doing some basic degging (like commenting out all the undefined index calls) tells me that there is an error. But there are no details as to what it is. Yes, not very helpful. I've checked the php error log, nothing. I've checked the install log, nothing of note (the last line is `X.X.X.X-,[04/Sep/2020:20:55:08 +0000],-,3.1.3,install,"QWcrm installation has begun.","",""`). Give me some pointers and I'll try to help.

**To Reproduce**
1. Follow the installer, get to the step where you are asked to create an administrator.
2. Fill in the details, any details in any combination. Hit next.

**Expected behavior**
I don't know, I've never got past this tep.

**Actual result**
` Whoops \ Exception \ ErrorException (E_NOTICE) Undefined index: error_component`
`/home/user/www/cache/smarty/compile/d97a0182876921f7be48bc5e91f5d1270b967ebb_0.file.error.tpl.php:34`

**System information (please complete the following information)**

Joomla version: ?
Kunena version: ?
Php version: 7.4
Database version: 10.3.22-MariaDB-1ubuntu1 Ubuntu 20.04

**Comment by shoulders** [comment]
this might be related to database strict standards
