### ISSUE TITLE
Print PDF button for invoice causes crash

### ISSUE THREAD

**Issue by mvnaylor** [shoulders/qwcrm#1801]
**Describe the bug**
When printing a PDF of an open invoice, the app crashes with the following error.
Whoops\Exception\ErrorException thrown with message "Trying to access array offset on value of type null"

Stacktrace:
#10 Whoops\Exception\ErrorException in /var/www/html/qwcrm/libraries/vendor/mpdf/mpdf/src/Otl.php:5794
#9 Whoops\Run:handleError in /var/www/html/qwcrm/libraries/vendor/mpdf/mpdf/src/Otl.php:5794
#8 Mpdf\Otl:trimOTLdata in /var/www/html/qwcrm/libraries/vendor/mpdf/mpdf/src/Tag/BlockTag.php:1093
#7 Mpdf\Tag\BlockTag:close in /var/www/html/qwcrm/libraries/vendor/mpdf/mpdf/src/Tag.php:250
#6 Mpdf\Tag:CloseTag in /var/www/html/qwcrm/libraries/vendor/mpdf/mpdf/src/Mpdf.php:13540
#5 Mpdf\Mpdf:WriteHTML in /var/www/html/qwcrm/libraries/qframework/qwcrm/System/Pdf.php:77
#4 Pdf:getMpdf in /var/www/html/qwcrm/libraries/qframework/qwcrm/System/Pdf.php:101
#3 Pdf:mpdf_output_in_browser in /var/www/html/qwcrm/components/invoice/print.php:97
#2 require in /var/www/html/qwcrm/libraries/qframework/qwcrm/System/Page.php:62
#1 Page:get_page_content in /var/www/html/qwcrm/libraries/qframework/qwcrm/System/Page.php:36
#0 Page:load_page in /var/www/html/qwcrm/index.php:99

**To Reproduce**
1. Open an invoice
2. Click the "Print PDF" button
3. New browser tab opens with error above.

**Expected behavior**
A new tab (or window) should open with a PDF of the invoice.

**Actual result**
Crash with error above.

**Screenshots**
![Screen Shot 2021-02-16 at 9 58 28 PM](https://user-images.githubusercontent.com/7556610/108150183-40da6700-70a2-11eb-94da-117361a02a91.png)

**System information (please complete the following information)**

QWcrm version: 3.1.3
Php version: 7.4.3
Database version: 3.1.3

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 88

**Comment by shoulders** [comment]
thanks for this.

I am sure this is an incompatiblity with mPDF and PHP 7.4 and will be addressed in the next release whn i update the library.

**Comment by shoulders** [comment]
I will update my xammp to php 7.4 and see if i get this error
