### ISSUE TITLE
overview counts incorrect

### ISSUE THREAD

**Issue by mvnaylor** [shoulders/qwcrm#1802]
On both the invoice and workorder overview pages, there seems to be a computation issue.

I have four "assigned", three "waiting for parts", and one "on hold" workorder which should total eight open workorders but the count is nine. See here:

![workorder overview](https://user-images.githubusercontent.com/7556610/108218549-c1c94b00-7102-11eb-85e1-7e5c7219128e.png)

I have five "unpaid" invoices which (I think) should match the number of "open" invoices but it shows 11 open.

![invoice overview](https://user-images.githubusercontent.com/7556610/108218790-03f28c80-7103-11eb-9f4f-e1e0b2806367.png)

Both of these may be related to the fact that I have deleted invoices and workorders and the computation does not take deleted items into account. Let me know what other details (likely some SQL queries) you need.

**Comment by shoulders** [comment]
- Well spotted. I can confirm my open work orders `index.php?component=workorder&page_tpl=overview` shows 1 extra WO and the invoice count might have the same issue.
- on the home page it shows the correct amount of work orders. however there is just me so they should match.
- the workorders show on the homepage are employee specific and the ones on the overview are global.

I appreciate the feedback.
