### ISSUE TITLE
Installation fatal error,  localhost with Xampp

### ISSUE THREAD

**Issue by argigonis** [shoulders/qwcrm#1807]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\rma\libraries\qframework\joomla\libraries\src\User\UserHelper.php on line 649

**Comment by argigonis** [comment]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\rma\libraries\qframework\joomla\libraries\src\User\UserHelper.php on line 649

**Comment by shoulders** [comment]
hanks for the feedback. i will be looking at QWcrm very soon.

**Comment by argigonis** [comment]
Thank you, Let me know if you find a solution about that.!
