### ISSUE TITLE
Stuck in installation.

### ISSUE THREAD

**Issue by SealPao** [shoulders/qwcrm#1808]
**Describe the bug**
I try to host QWcrm on my NAS, but can go through the process.
Here's my log

192.168.68.169,-,[29/Dec/2021:16:33:32 +0800],-,3.1.3,install,"The database installation process was successful.","",""
192.168.68.169,-,[29/Dec/2021:16:33:32 +0800],-,3.1.3,install,"The database installed successfully.","",""
192.168.68.169,-,[29/Dec/2021:16:33:37 +0800],-,3.1.3,install,"QWcrm installation has begun.","",""
192.168.68.169,-,[29/Dec/2021:16:33:37 +0800],-,3.1.3,correction,"Failed to update the value for the record `year_start` to `2021-12-29` in the table `gnjc_company_record` ","Table 'bb_qwcrm.gnjc_company_record' doesn't exist",""
192.168.68.169,-,[29/Dec/2021:16:33:37 +0800],-,3.1.3,correction,"Failed to update the value for the record `year_end` to `2022-12-29` in the table `gnjc_company_record` ","Table 'bb_qwcrm.gnjc_company_record' doesn't exist",""

QWcrm version: 3.1.3
Php version:7.4
Database version:

**Comment by SealPao** [comment]
I am using Synology NAS with DS7.0 to host the site.
I have MariaDB10 as database.

I tried Apache HTTP server 2.2 and 2.4 all got the same result.

**Comment by shoulders** [comment]
i will be doing some development work shortly. It might be to do with the strict settings on the server.

https://github.com/shoulders/qwcrm/issues/1712
