### ISSUE TITLE
Login Failed. Check you username and password.

### ISSUE THREAD

**Issue by argigonis** [shoulders/qwcrm#1809]
Istallation on cpanel linux

Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.32-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
User: 
Server charset: UTF-8 Unicode (utf8)

cpsrvd 11.100.0.5
Database client version: libmysql - 5.6.43
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.3.33
PHPmyAdmin: Version information: 4.9.7

ERROR LOG
 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/so337206/public_html/RMACRM/components/_includes/Voucher.php on line 918

 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/so337206/public_html/RMACRM/components/_includes/Setup.php on line 1031

I changed the curl braces with square braces on the lines 918 , 1031 and nothing changed

what should i do about it

**Comment by shoulders** [comment]
duplicate issue / same cause #1807
