### ISSUE TITLE
Add EURO (€) to currency

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#412]
Add EURO (€) to currency in Business Setup.

**Comment by shoulders** [comment]
already added
![euro](https://user-images.githubusercontent.com/319997/28921153-b232f252-784c-11e7-9487-90093eb55af4.JPG)

if you mean this list

USD" = US Dollars, "AUD" = Australian Dollars, "GBP" = British Pound.

can you give me the EURO 3 letter code

**Comment by AlduinNL** [comment]
Yes, it is: "EUR".
