### ISSUE TITLE
EURO symbol not supported

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#414]
Euro symbol not support, like in the old MyITCRM.

![image](https://user-images.githubusercontent.com/29981640/28923124-39dd67f4-785d-11e7-962f-ea98484bd0e8.png)

**Comment by shoulders** [comment]
ahh, let me look into this for you

**Comment by shoulders** [comment]
the database is not encoding this properly. i could potentials use escaped html entities 

https://www.w3schools.com/charsets/ref_utf_currency.asp
