### ISSUE TITLE
Payment Options gives error

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#415]
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

**Comment by shoulders** [comment]
how did you get this error? what did you do?

**Comment by AlduinNL** [comment]
Error is displayed when Payment Options is clicked in the Menu.

**Comment by shoulders** [comment]
I see the issue. I will investigate

**Comment by shoulders** [comment]
this was caused because i truncated the table and the update functions are just that, update only, no insert. I needed to create a blank entry to which the code could then update. I dont know why it fails
