### ISSUE TITLE
Time and date editor buttons

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#428]
Timestamp not available anymore in the new text editor. Is it possible to automatically insert time and date, when clicking the edit button?

**Comment by shoulders** [comment]
timestamp was never available, do you mean the date?

if so can you highlight the button on the old editor for me please. 

I have never used this feature, but i can have a look

**Comment by shoulders** [comment]
do you mean these buttons
![timestamp](https://user-images.githubusercontent.com/319997/29007258-e2fc89a0-7af6-11e7-9548-aa51dd09edf3.JPG)

**Comment by AlduinNL** [comment]
Yes, I mean those! :)
