### ISSUE TITLE
Financial Report shows error

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#469]
When opening Financial Report and selecting the period, an error comes up.

Error Page: report:financial
Error Type: database

Error Location: includes/modules/report.php
PHP Function: sum_total_quantity_of_labour_items_in_selected_period()

Database Error: Unknown column 'invoice_labour_unit' in 'field list'
SQL Query: 
SELECT SUM(invoice_labour_unit) AS sum FROM qw_invoice_labour INNER JOIN qw_invoice ON qw_invoice.invoice_id = qw_invoice_labour.invoice_id WHERE qw_invoice.date >= '1501545600' AND qw_invoice.date <= '1503532800'

Error Message: Failed to return the total number of labour items ordered in the selected period.

**Comment by shoulders** [comment]
fixed in new version
