### ISSUE TITLE
Print PDF shows error

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#472]
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: Cannot modify header information - headers already sent by (output started at /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php:4082) in /home/svchost1/public_html/qwcrm/libraries/mpdf/mpdf.php on line 9403

Fatal error: Uncaught exception 'MpdfException' with message 'Some data has already been output to browser, can't send PDF file' in /home/svchost1/public_html/qwcrm/libraries/mpdf/mpdf.php:9405 Stack trace: #0 /home/svchost1/public_html/qwcrm/includes/mpdf.php(17): mPDF->Output() #1 /home/svchost1/public_html/qwcrm/modules/invoice/print.php(48): require_once('/home/svchost1/...') #2 /home/svchost1/public_html/qwcrm/index.php(387): require('/home/svchost1/...') #3 {main} thrown in /home/svchost1/public_html/qwcrm/libraries/mpdf/mpdf.php on line 9405

**Comment by shoulders** [comment]
fixed in new version
