### ISSUE TITLE
Print button shows error

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#473]
When choosing the Print button (not the Print PDF one), the example shows warnings.

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4082

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/svchost1/public_html/qwcrm/libraries/adodb/adodb.inc.php on line 4084

![image](https://user-images.githubusercontent.com/29981640/29660952-f2fd3186-88c2-11e7-9fb3-fc6a970d7e57.png)

**Comment by shoulders** [comment]
fixed in new version
