### ISSUE TITLE
Hits stats by IP shows error

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#475]
Error Page: stats:hit_stats_by_ip
Error Type: database

Error Location: includes/modules/stats.php
PHP Function: display_hits_by_ip()

Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY date' at line 1
SQL Query: 
SELECT * FROM qw_tracker WHERE ip=NULLORDER BY date

Error Message: Failed to return hits by IP.

**Comment by shoulders** [comment]
this old style tracker has been removed. new tracker that is in apache log format
