### ISSUE TITLE
undefined variable Qconfig in index.php on line 142

### ISSUE THREAD

**Issue by shabbir92** [shoulders/qwcrm#534]
dear shoulders  thank you very much for work on this project, today i have tried to install for test. it seems it is not complete yet, because there is no file configuration.php, when i try to access it with this url  localhost/crm/index.php  it showed me error
 ` undefined variable Qconfig in index.php on line 142.`
and i am unable to install it

**Comment by shoulders** [comment]
I am just putting the final touches to the first release which will require testing. should be a couple of days, until then there will be changes to the code giving errors like this.

**Comment by shoulders** [comment]
if you contact me throught my website quantumwarp.com i can send you out a copy of testing when the first verision is ready for testing, hopefully within a week.
