### ISSUE TITLE
Can't use special characters

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#582]
At the new customer page: display name.

Can't use for example a . (dot), when I only want to use initials for the customer.
For example: K. Test.

![image](https://user-images.githubusercontent.com/29981640/30738419-4f154bc4-9f8a-11e7-8a93-c3f28cc3e7b6.png)

**Comment by shoulders** [comment]
aah ok. Are there any other special character you  want to use. I need to see which are allowed.

so far the following have been suggested

. (dot)
' (apostrophe)

**Comment by AlduinNL** [comment]
Only the dot is my suggestion :)
