### ISSUE TITLE
Automatic time/date stamp

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#583]
Automatic time/date stamp, so we don't have to manually click the date/time buttons.

![image](https://user-images.githubusercontent.com/29981640/30738503-9835e5a2-9f8a-11e7-8b2b-e4c61f8318bd.png)

**Comment by shoulders** [comment]
when you close the workorder a time is automatically as the closed date. Is this want you mean?

**Comment by AlduinNL** [comment]
No. I mean: when adding a description or resolution (clicking in the text field).

**Comment by shoulders** [comment]
changed are logged in the workorder history giving you times when things were changed/updated but you will need to use the button to add the timestamp into the description etc..

The description and resolution appear on the invoice when one is created and also if you updated the description it would add another timestamp onto the description and would quickly look messy.

**Comment by shoulders** [comment]
anything in the description needs to be filled in manually.

logging does occur in work order history
![history](https://user-images.githubusercontent.com/319997/30772106-f5a65966-a04c-11e7-9a06-665b8faea5ed.png)
