### ISSUE TITLE
Can't print WO

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#584]
Some or all of the Printing Options are not set.

**Comment by shoulders** [comment]
I will examine this. can you give me the page from where you click on this.

replace the demo domain with example.com so the demo site stays hidden

thanks

**Comment by AlduinNL** [comment]
Link is: http://www.svchost.co.uk/qwcrm/index.php?page=workorder:print&workorder_id=1&theme=off

**Comment by shoulders** [comment]
i need the page which the button was one, not the actually link.

use example.com

tar

**Comment by shoulders** [comment]
found it

![print_wo](https://user-images.githubusercontent.com/319997/30744211-f37f59ee-9f98-11e7-82e1-5304b6a723d3.JPG)

there are also these different printouts
![icons](https://user-images.githubusercontent.com/319997/30744277-3bcc11b0-9f99-11e7-8a9c-b26d655a11b8.jpg)
