### ISSUE TITLE
Error when clicking: New Note at the menu

### ISSUE THREAD

**Issue by AlduinNL** [shoulders/qwcrm#608]
When viewing the workorder and clicking the New Note button in the menu, the following page shows with a 404 error:

![image](https://user-images.githubusercontent.com/29981640/30854924-71dc2d40-a2b3-11e7-9a79-98add72cd24b.png)

 /qwcrm/index.php?page=workorder:details&workorder_id=1

**Comment by shoulders** [comment]
you can add and edit notes via the icons on the notes tab in workorder details so i will remove this link. only major items should be in the menu
