### ISSUE TITLE
Errors instead of installer

### ISSUE THREAD

**Issue by disorganised-mess** [shoulders/qwcrm#756]
Considering you've released v3.0.0, is there an official/proper method for installation? There doesn't seem to be a 'setup' script or a procedure for getting this to 'install' and be functional. I setup xampp with a database for a new install pointed my browser at the directory, which is the method used for MYITCRM, but there is no 'setup' file to run. This is what I get:
![screenshot-2017-11-17 http localhost](https://user-images.githubusercontent.com/15573579/32959946-377b58c2-cb91-11e7-9e14-9931b48adb02.png)
Without a described manual editing procedure, how does one get this to work?

**Comment by shoulders** [comment]
hi

I needed to release the software so I could get to the documentation and website. Rather than wait until I did the documentation I tought I would release it first. Instructions will be getting done very soon.

**questions**
- what version of xampp are you using
- what version of php and mysql?
- 'Without a described manual editing procedure' - do you mean instructions?

**what i can see**
- I can see some issues and will fix these issues tomorrow. 
- the functions locale_accept_from_http() needs to be enabled in xampp via the php.ini, i will give some brief instructions for this.
- I will install the exact same version of xampp that you are using to find out what is going on.

thanks for reporting the issue. I will get my forum open this weekend if all goes well.

**Comment by disorganised-mess** [comment]
Using xampp for Windows v7.1.10, PHP v7.1.10, MySQL v5.0.12.
Trying a fresh install, wanted to see it before migration.
Yes I meant instructions. Used other projects where manual editing of a configuration file was all that was needed to make the software work. I just didn't see an easy option for that with QWcrm. I also recall editing needing done with the original MYITcrm, so no stranger to that. 
You've done a lot of work on this and I've been looking forward to it, your effort is greatly appreciated.
Looking at initial setup with XAMPP, but will also be setting up a Raspberry Pi for this as a more permanent home once I sort out some of my lab.

**Comment by shoulders** [comment]
just a quick one, did you create the configuration.php manually? The configuration.php is created automatically during setup. If you did you will need to delete it.

to enable the locale_accept_from_http() edit your php.ini and uncomment out
````
;extension=php_intl.dll
````

If this all works, the simple migration (please backup and test etc..) for MyITCRM is:

- delete all MyITCRM files (if you are putting QWcrm in the same place)
- copy all of the QWcrm into the same folder or wherever you want
- with phpmyadmin make sure the default collation is set to **utf8_unicode_ci** under the operations tab for the database  ![image](https://user-images.githubusercontent.com/319997/32971811-e6bfe6c2-cbe6-11e7-9908-93642674642d.png)
- start QWcrm by browsing to the folder you just put it in and select migrate from MyITCRM
- the migrator will install QWcrm with the migrated data into the same database as your old MyITCRM database.

**Comment by shoulders** [comment]
**Solution for xampp** - most servers will not have this issue
In php.ini
- uncomment **;extension=php_intl.dll** to enable the function locale_accept_from_http()
- reduce error reporting - **error_reporting = E_ALL & ~E_NOTICE**
- restart xampp

**To Explain**
- locale_accept_from_http() is required to auto-detect your browser language and is not turned on by default in xampp but is on most real webservers by default
- The error reporting is reduced to remove all the notices of non-existent variables. These errors will get removed 'hopefully' in the next release. They cause no issues with how the program works, but for now this is the best way of fixing them. This is also a standard setting most web companies use.

**Comment by disorganised-mess** [comment]
Stellar, changing those settings made everything work perfect. Again thanks for all your hard work. I did a fresh install rather than a migration. The MYITcrm I'm currently using has been moved around between a few computers that I wanted a nice clean install to start working from again. If you don't mind I closed this issue after this comment. Great work.
