### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by lucianodato** [shoulders/qwcrm#779]
Hi! Thanks for modernizing this useful crm! I'm trying to install it in an ubuntu server 16.04 with a lamp stack but I can't make it work. Is there anything special that I need to do? How are you supposed to install it?

**Comment by shoulders** [comment]
There is nothing special you should do. screenshots and error messages would be helpful. Next couple of days I will be opening my forum at https://quantumwarp.com/. If you drop me a line via my contact page I can help you there for now if that is ok.

**Comment by shoulders** [comment]
my contact form is dodgy, typical.

You can post your issues here for now.

**Comment by lucianodato** [comment]
Did all that already and no luck. Unfortunately I only see a blank page when accessing the site folder. My stack consist in the basic lamp ubuntu server has. That is mysql 5.7.21, php 7.0.28 and apache 2.4.18. What I did is the following:
- Download the latest release in /var/www/html and extract in a new folder called qwcrt
- Chmod the folder and its files to be owned by www-data user and group
- Create the database called technae_qwcrm and change to utf8
- Access to some_internal_ip_without_firewalls_present/qwcrm
- Blank page appears
That's all I did. Did I miss anything else?

**Comment by shoulders** [comment]
Some of the stuff I do not know about because I have not used Ubuntu. But we need to see what errors are occuring. You need to turn on php error reporting and see what error messages are coming up.

**One way that might work**

if you do not know your way around am server/php settings is to alter one of the QWcrm files.

/includes/error.php

change `switch ($QConfig->error_reporting)` to `switch ('maximum')`

This should work but i cannot gurantee without testing it myself.

**option 2**
configure you php.ini to display errors

**Comment by lucianodato** [comment]
Ok this is what I got: 
array(4) { ["type"]=> int(1) ["message"]=> string(196) "Uncaught Error: Call to undefined function locale_accept_from_http() in /var/www/html/qwcrm/includes/language.php:25 Stack trace: #0 /var/www/html/qwcrm/index.php(81): require() #1 {main} thrown" ["file"]=> string(41) "/var/www/html/qwcrm/includes/language.php" ["line"]=> int(25) }

**Comment by shoulders** [comment]
> That is all that is needed to install on a webhost. Xampp needs a few more settings see the second to last post #756 

Althought it is for xampp it should be the same fix for you.

I might try and add in some better logic for checking this.

**Comment by lucianodato** [comment]
Did what you recommend in #756 and no luck. I get the same error message.

**Comment by shoulders** [comment]
Is it available public online (and hoepfully a non vital server). I am quite happy to dial in and have a look. I would need ftp access etc..

**Disclaimer:** I accept no reponsibility for data loss or damage etc...

It might be this function has been removed in PHP 7.x but I would need to verify this and fix it.

You can contact me via my contact form on Quantumwarp.com . I cannot find a PM system on GitHub.

**Comment by lucianodato** [comment]
No worries It's a test VM. I'm just looking to this CRM in order to implement it at my work. Thanks very much for your support up to now but I prefer to look it myself. Anyways I will respond back when I got something useful for you. Again thanks!

**Comment by shoulders** [comment]
I will be moving QWcrm to another Github username shortly (qwarp) and enabling my forum but I will still be available. Look forwarding to the fix.

**Comment by shoulders** [comment]
did you get this fixed?

If not i can maybe make an altered file to remove the automatic language detection so you dont get that error. This would be a hack so you can get things working but would not affect databases.

**Comment by lucianodato** [comment]
I'm sorry I didn't had time to try yet. Tomorrow I will work on that. Thanks!

**Comment by lucianodato** [comment]
Well it seems that php7.0-intl (enables internationalization) package is needed and ubuntu won't install it by default when you install it with tasksel. That was it. Now the installer is working as it should. Thanks for your support!

**Comment by lacrimosa2k2** [comment]
i can´t find the error.php in the actual branche

**Comment by lacrimosa2k2** [comment]
> 
> The branch is not working. It is in development. New version out soon. Use v3.0.0 from releases.
> […](#)
> On 6 November 2018 21:49:27 GMT+00:00, lacrimosa2k2 ***@***.***> wrote: i can´t find the error.php in the actual branche -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#779 (comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436421041)
> -- Sent from my Android phone with K-9 Mail. Please excuse my brevity.

okay thaks, my fail.
but i have Upload the 3.0 and in the setup after creating database it shows a withe scren, and than it says "A previous setup attempt never completed successfully and/or there is an invalid configuration.php file present or the database prefix is wrong." but i cant find this file. i deleted all and start a new setup and again this message

**Comment by shoulders** [comment]
Delete all files and make sure they are deleted. Reupload. Close your browser and start again.

The configuration.php is created after the database stage. Once the process is started you have to finish. You can not click back on the browser. It will all be ajax in v3.2.0.

On 6 November 2018 23:06:45 GMT+00:00, lacrimosa2k2 <notifications@github.com> wrote:
>> >
>> The branch is not working. It is in development. New version out
>soon. Use v3.0.0 from releases.>
>> […](#)>
>> On 6 November 2018 21:49:27 GMT+00:00, lacrimosa2k2 ***@***.***>
>wrote: i can´t find the error.php in the actual branche -- You are
>receiving this because you commented. Reply to this email directly or
>view it on GitHub: [#779
>(comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436421041)>
>> -- Sent from my Android phone with K-9 Mail. Please excuse my
>brevity.>
>>
>okay thaks, my fail.>
>but i have Upload the 3.0 and in the setup after creating database it
>shows a withe scren, and than it says "A previous setup attempt never
>completed successfully and/or there is an invalid configuration.php
>file present or the database prefix is wrong." but i cant find this
>file. i deleted all and start a new setup and again this message
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/779#issuecomment-436442310

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by lacrimosa2k2** [comment]
> 
> Delete all files and make sure they are deleted. Reupload. Close your browser and start again. The configuration.php is created after the database stage. Once the process is started you have to finish. You can not click back on the browser. It will all be ajax in v3.2.0.
> […](#)
> On 6 November 2018 23:06:45 GMT+00:00, lacrimosa2k2 ***@***.***> wrote: > > > The branch is not working. It is in development. New version out soon. Use v3.0.0 from releases.> > […](#)> > On 6 November 2018 21:49:27 GMT+00:00, lacrimosa2k2 ***@***.***> wrote: i can´t find the error.php in the actual branche -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#779 (comment)]([#779 (comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436421041))> > -- Sent from my Android phone with K-9 Mail. Please excuse my brevity.> > okay thaks, my fail.> but i have Upload the 3.0 and in the setup after creating database it shows a withe scren, and than it says "A previous setup attempt never completed successfully and/or there is an invalid configuration.php file present or the database prefix is wrong." but i cant find this file. i deleted all and start a new setup and again this message -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#779 (comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436442310)
> -- Sent from my Android phone with K-9 Mail. Please excuse my brevity.

yes i have tried to start a fresh install, with the same result. the configuration.php isnt there. can it a permission problem?

**Comment by shoulders** [comment]
I don't think it is permissions because qwcrm changes the permissions on the file.

If you can sort some details for me to ftp in to your server and give me some database credentials etc..  I can have a look tomorrow and see why it is not working.

 Don't give me your main details so I cannot break any of your live website etc... A demo server is best.

I cannot workout if you are using github private message or comments. My website quantumwarp.com is a good place to send details via the contact form if this is not private.

Cheers

Shoulders

On 6 November 2018 23:12:57 GMT+00:00, lacrimosa2k2 <notifications@github.com> wrote:
>> >
>> Delete all files and make sure they are deleted. Reupload. Close your
>browser and start again. The configuration.php is created after the
>database stage. Once the process is started you have to finish. You can
>not click back on the browser. It will all be ajax in v3.2.0.>
>> […](#)>
>> On 6 November 2018 23:06:45 GMT+00:00, lacrimosa2k2 ***@***.***>
>wrote: > > > The branch is not working. It is in development. New
>version out soon. Use v3.0.0 from releases.> > […](#)> > On 6 November
>2018 21:49:27 GMT+00:00, lacrimosa2k2 ***@***.***> wrote: i can´t find
>the error.php in the actual branche -- You are receiving this because
>you commented. Reply to this email directly or view it on GitHub: [#779
>(comment)]([#779
>(comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436421041))>
>> -- Sent from my Android phone with K-9 Mail. Please excuse my
>brevity.> > okay thaks, my fail.> but i have Upload the 3.0 and in the
>setup after creating database it shows a withe scren, and than it says
>"A previous setup attempt never completed successfully and/or there is
>an invalid configuration.php file present or the database prefix is
>wrong." but i cant find this file. i deleted all and start a new setup
>and again this message -- You are receiving this because you commented.
>Reply to this email directly or view it on GitHub: [#779
>(comment)](https://github.com/shoulders/qwcrm/issues/779#issuecomment-436442310)>
>> -- Sent from my Android phone with K-9 Mail. Please excuse my
>brevity.>
>>
>yes i have tried to start a fresh install, with the same result. the
>configuration.php isnt there. can it a permission problem?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoulders/qwcrm/issues/779#issuecomment-436443785

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by shoulders** [comment]
i have just installed QWcrm v3.0.0 and I do not have the same issue. perhaps you are clicking on the browser back button.

Open another issue here if you need more support. I will sort my forum out going forward.

**Comment by jpventer85** [comment]
hi, new to github and qwcrm , is there someone that will perhaps help with the installation i cant seem to get it, and if tried everything, not sure if im missing a step.

**Comment by shoulders** [comment]
I will try and post a some tommorow. I have to dig them out.

**Comment by jpventer85** [comment]
Thanx. Ive tried everything. I cant seem to get to the install page so let
me tell u what i did. So i have the sub domain. I copy the files to the
folder. Extracted did the mysql username. Change the col size as stated.
The if i go to the url just say erorr 404.

If u can help souds like a great app though.  Perhaps im geting it wrong
can i install in on a blank page or do i need joomla?

**Comment by shoulders** [comment]
see https://github.com/shoulders/qwcrm/issues/1984
