### ISSUE TITLE
Installation issue 'This page isn't working'

### ISSUE THREAD

**Issue by ahoquegh** [shoulders/qwcrm#911]
Hello,
I spend several hours to bring up the qwcrm. I followed your suggestions and had done the followngs
•Download the latest release in /var/www/html and extract in a new folder called qwcrm
•Chmod the folder and its files to be owned by www-data user and group
•Create the database called test_qwcrm and change to utf8
• tried sample index.htm file to make sure apache2 works.
• But once I tried surf to /var/ww/html/qwcrm/src I am seeing "This page isn't working" and HTML error 500

Here is the errors I am seeing in the apache2 error.log. Appreciate any debug suggestion:

[Thu Jun 07 19:54:49.889854 2018] [core:notice] [pid 1231] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jun 07 20:01:38.888896 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Undefined variable: QConfig in /var/www/html/qwcrm/src/includes/defines.php on line 18, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.888935 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Trying to get property of non-object in /var/www/html/qwcrm/src/includes/defines.php on line 18, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.888951 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Undefined variable: QConfig in /var/www/html/qwcrm/src/includes/defines.php on line 42, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.888959 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Trying to get property of non-object in /var/www/html/qwcrm/src/includes/defines.php on line 42, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.889177 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Undefined variable: QConfig in /var/www/html/qwcrm/src/includes/error.php on line 19, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.889193 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Notice:  Trying to get property of non-object in /var/www/html/qwcrm/src/includes/error.php on line 19, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.889274 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Warning:  require(libraries/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/qwcrm/src/index.php on line 74, referer: http://192.168.0.12/qwcrm/
[Thu Jun 07 20:01:38.889299 2018] [:error] [pid 1279] [client 192.168.0.2:51454] PHP Fatal error:  require(): Failed opening required 'libraries/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/qwcrm/src/index.php on line 74, referer: http://192.168.0.12/qwcrm/

**Comment by shoulders** [comment]
Hi ahoquegh,

- You need to download QWcrm-3.0.0.zip
- You say you extracted to /var/ww/html/qwcrm/ but you are trying to run /var/ww/html/qwcrm/src/ . This folder does not exist in 3.0.0

can you confirm what version you are using?

shoulders

**Comment by ahoquegh** [comment]
Hi shoulders,
Thanks for responding so quickly.  
I downloaded the zip file from github (https://github.com/shoulders/qwcrm). It does not look like QWcrm-3.0.0
This morning I did try to unsuccessfully download QWcrm-3.0.0 from your website https://quantumwarp.com/downloads/download/20-qwcrm/9-qwcrm. Not seeing the file. Please let me know the right location to download it from. thanks

**Comment by shoulders** [comment]
try this.

https://github.com/shoulders/qwcrm/releases/download/3.0.0/QWcrm-3.0.0.zip

**Comment by shoulders** [comment]
no response

**Comment by ahoquegh** [comment]
Thanks a lot for the help. yes it worked. (sorry for the late reply)

**Comment by shoulders** [comment]
new version will be out shortly. then after that it is getting a template upgrade.

Glad it worked out.
